controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    jnt_pos_cont:
      type: joint_trajectory_controller/JointTrajectoryController

diff_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_link

    wheel_separation: 1.0
    wheel_radius: 0.3045

    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    
jnt_pos_cont:
  ros__parameters:
    joints:
      - right_diff_unit_joint
      - left_diff_unit_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_broad:
    ros__parameters:
      publish_rate: 50.0
      joint_names: ['right_diff_unit_joint', 'left_diff_unit_joint']